
import {
  CONFIDENCE_LEVEL,
  MONEY_STATUS,
  VISIBILITY_LEVEL,
} from "./securityIntelligence";

export const OWNER_MONEY_PACK = {
  pack: "050D-A",
  name: "Owner Money Foundation",
  status: "foundation_ready",
  opensFrom: "The Tower",
  scope: "money_only",
};

export const ownerThemeChoices = {
  velvetBloom: {
    key: "velvetBloom",
    name: "Velvet Bloom",
    vibe: "moody, femme, soft-rich",
    bg: "#211827",
    bg2: "#34233D",
    card: "#51305D",
    panel: "#43294E",
    ink: "#FFF6FB",
    muted: "#E8CFE5",
    primary: "#FF9ED8",
    secondary: "#BFA4FF",
    third: "#FFD166",
    warning: "#FFB86B",
    good: "#A7F3D0",
  },
  fairyLedger: {
    key: "fairyLedger",
    name: "Fairy Ledger",
    vibe: "enchanted bookkeeping",
    bg: "#15251F",
    bg2: "#22372F",
    card: "#35584A",
    panel: "#2D4A3F",
    ink: "#F7FFF9",
    muted: "#D4ECDD",
    primary: "#A7F3D0",
    secondary: "#C4B5FD",
    third: "#FDE68A",
    warning: "#FDBA74",
    good: "#86EFAC",
  },
  moonJelly: {
    key: "moonJelly",
    name: "Moon Jelly",
    vibe: "dreamy blue, pearl glow",
    bg: "#101B2D",
    bg2: "#172B45",
    card: "#29466E",
    panel: "#213A5C",
    ink: "#F5FBFF",
    muted: "#C9DFF2",
    primary: "#8BD3FF",
    secondary: "#B8C0FF",
    third: "#D7F9FF",
    warning: "#FCD34D",
    good: "#A7F3D0",
  },
  sugarPlumVault: {
    key: "sugarPlumVault",
    name: "Sugar Plum Vault",
    vibe: "plum, rose-gold, rich but playful",
    bg: "#271421",
    bg2: "#3A1F35",
    card: "#5C3355",
    panel: "#4A2945",
    ink: "#FFF7FC",
    muted: "#E8C8DD",
    primary: "#F9A8D4",
    secondary: "#F0ABFC",
    third: "#FCD34D",
    warning: "#FDBA74",
    good: "#BBF7D0",
  },
  cherryCircuit: {
    key: "cherryCircuit",
    name: "Cherry Circuit",
    vibe: "dark cherry, cute tech",
    bg: "#180D16",
    bg2: "#26111F",
    card: "#4A1F3D",
    panel: "#3A1930",
    ink: "#FFF5FB",
    muted: "#E8C6DA",
    primary: "#FB7185",
    secondary: "#F472B6",
    third: "#67E8F9",
    warning: "#FBBF24",
    good: "#86EFAC",
  },

  cosmicLemonade: {
    key: "cosmicLemonade",
    name: "Cosmic Lemonade",
    vibe: "zesty, starry, cheerful but not childish",
    bg: "#161B2E",
    bg2: "#252B46",
    card: "#323858",
    panel: "#272E4D",
    ink: "#FFFDF2",
    muted: "#E7E1C7",
    primary: "#FDE047",
    secondary: "#93C5FD",
    third: "#F9A8D4",
    warning: "#FDBA74",
    good: "#A7F3D0",
  },
  moneyMermaid: {
    key: "moneyMermaid",
    name: "Money Mermaid",
    vibe: "aquatic, pearly, rich soft-blue",
    bg: "#082A33",
    bg2: "#123E4A",
    card: "#1B5966",
    panel: "#164A56",
    ink: "#F3FDFF",
    muted: "#C6EAF0",
    primary: "#67E8F9",
    secondary: "#A7F3D0",
    third: "#F0ABFC",
    warning: "#FCD34D",
    good: "#86EFAC",
  },
  peachPortal: {
    key: "peachPortal",
    name: "Peach Portal",
    vibe: "soft peach, dreamy, friendly money magic",
    bg: "#2A1718",
    bg2: "#432423",
    card: "#653630",
    panel: "#57302D",
    ink: "#FFF7F2",
    muted: "#F2CFC3",
    primary: "#FDBA74",
    secondary: "#F9A8D4",
    third: "#FDE68A",
    warning: "#F97316",
    good: "#BBF7D0",
  },
  royalBubblegum: {
    key: "royalBubblegum",
    name: "Royal Bubblegum",
    vibe: "bold pink, royal blue, playful luxury",
    bg: "#151331",
    bg2: "#242052",
    card: "#322A6B",
    panel: "#29245D",
    ink: "#FFF6FF",
    muted: "#D9D1FF",
    primary: "#FF8BD1",
    secondary: "#7DD3FC",
    third: "#FDE047",
    warning: "#FDBA74",
    good: "#A7F3D0",
  },
  emeraldOpera: {
    key: "emeraldOpera",
    name: "Emerald Opera",
    vibe: "deep green, dramatic, expensive",
    bg: "#061E18",
    bg2: "#0B3328",
    card: "#144A3A",
    panel: "#103C30",
    ink: "#F3FFF9",
    muted: "#BFE8D5",
    primary: "#34D399",
    secondary: "#FDE68A",
    third: "#C4B5FD",
    warning: "#FBBF24",
    good: "#86EFAC",
  },
  blueberryVelvet: {
    key: "blueberryVelvet",
    name: "Blueberry Velvet",
    vibe: "soft navy, velvety, low-stim luxury",
    bg: "#0B1026",
    bg2: "#151C3A",
    card: "#202A52",
    panel: "#1A2448",
    ink: "#F7FAFF",
    muted: "#CBD7F5",
    primary: "#93C5FD",
    secondary: "#C4B5FD",
    third: "#F9A8D4",
    warning: "#FCD34D",
    good: "#A7F3D0",
  },
  strawberryMoon: {
    key: "strawberryMoon",
    name: "Strawberry Moon",
    vibe: "romantic red-pink, moonlit, soft drama",
    bg: "#201018",
    bg2: "#351827",
    card: "#4D2438",
    panel: "#3F1D2F",
    ink: "#FFF7FA",
    muted: "#EBC5D3",
    primary: "#FB7185",
    secondary: "#F9A8D4",
    third: "#FDE68A",
    warning: "#FDBA74",
    good: "#BBF7D0",
  },
  chromeFairy: {
    key: "chromeFairy",
    name: "Chrome Fairy",
    vibe: "silver-lilac, futuristic, airy",
    bg: "#141725",
    bg2: "#202437",
    card: "#2D3148",
    panel: "#252A3F",
    ink: "#FAFBFF",
    muted: "#D4D8EA",
    primary: "#D8B4FE",
    secondary: "#BAE6FD",
    third: "#E5E7EB",
    warning: "#FCD34D",
    good: "#A7F3D0",
  },
  lavenderOrbit: {
    key: "lavenderOrbit",
    name: "Lavender Orbit",
    vibe: "spacey lavender, soft gold",
    bg: "#171629",
    bg2: "#222044",
    card: "#393371",
    panel: "#2E2A5F",
    ink: "#FAF7FF",
    muted: "#DAD2F7",
    primary: "#C4B5FD",
    secondary: "#F9A8D4",
    third: "#FDE68A",
    warning: "#FDBA74",
    good: "#A7F3D0",
  },
};

export const ownerProfile = {
  name: "Solice",
  ownerId: "OWNER-777001",
  defaultTheme: "velvetBloom",
  clearance: "owner",
  towerRequired: true,
};

export const ownerSnapshotCards = [
  {
    key: "trust",
    label: "Trust",
    title: "Simplee Bowdre Trust",
    value: "Owner money layer",
    detail: "Capital contributions, ownership records, protected money documents, and later distributions.",
    status: MONEY_STATUS.TOWER_REQUIRED,
    source: "owner_record",
    confidence: CONFIDENCE_LEVEL.TOWER_GATED,
    visibility: VISIBILITY_LEVEL.OWNER_ONLY,
    color: "#FFD166",
  },
  {
    key: "simpleepay",
    label: "SimpleePay",
    title: "Payroll money",
    value: "$4.8k payroll",
    detail: "Pay cycles, tax/payment records, employee changes, payroll packets, and proof.",
    status: MONEY_STATUS.NEEDS_REVIEW,
    source: "payroll_record",
    confidence: CONFIDENCE_LEVEL.NEEDS_PROOF,
    visibility: VISIBILITY_LEVEL.OWNER_ONLY,
    color: "#92D7C8",
  },
  {
    key: "mrktrade",
    label: "MrkTrade",
    title: "Protected financial paperwork",
    value: "$50.0k snapshot",
    detail: "Vague owner numbers, expenses, deposits, paperwork, receipts, and Tower handoffs only. No OB doorway.",
    status: MONEY_STATUS.TOWER_REQUIRED,
    source: "tower_gated_snapshot",
    confidence: CONFIDENCE_LEVEL.TOWER_GATED,
    visibility: VISIBILITY_LEVEL.TOWER_REQUIRED,
    color: "#BFA4FF",
  },
  {
    key: "skincare",
    label: "SimpleeSkincare",
    title: "Business money",
    value: "$2.6k snapshot",
    detail: "Sales, payment totals, costs, fees, refunds, deposits, shipping spend, and proof records only.",
    status: MONEY_STATUS.NEEDS_REVIEW,
    source: "manual_money_snapshot",
    confidence: CONFIDENCE_LEVEL.ESTIMATED,
    visibility: VISIBILITY_LEVEL.OWNER_ONLY,
    color: "#FF9ED8",
  },
  {
    key: "onthego",
    label: "SimpleeOnTheGo",
    title: "Route money",
    value: "$8.1k tracked",
    detail: "Route revenue, location fees, cash needs, machine costs, payments, and route proof.",
    status: MONEY_STATUS.PROOF_MISSING,
    source: "route_money_record",
    confidence: CONFIDENCE_LEVEL.NEEDS_PROOF,
    visibility: VISIBILITY_LEVEL.OWNER_ONLY,
    color: "#5EEAD4",
  },
  {
    key: "property",
    label: "SimpleeProperty",
    title: "Property money",
    value: "$12.4k income",
    detail: "Income, vendor bills, reserves, repairs, taxes, insurance, and property paperwork.",
    status: MONEY_STATUS.NEEDS_REVIEW,
    source: "property_money_record",
    confidence: CONFIDENCE_LEVEL.ESTIMATED,
    visibility: VISIBILITY_LEVEL.OWNER_ONLY,
    color: "#A7C7E7",
  },
];

export const ownerMoneyQueue = [
  {
    key: "payroll-readiness",
    lane: "Pay People",
    business: "SimpleePay",
    title: "Payroll run needs final readiness",
    amount: "$4.8k",
    due: "Today",
    status: MONEY_STATUS.NEEDS_REVIEW,
    source: "payroll_record",
    confidence: CONFIDENCE_LEVEL.NEEDS_PROOF,
    visibility: VISIBILITY_LEVEL.OWNER_ONLY,
    priority: 100,
    action: "Review payroll records",
    why: "Payroll should not move until employee changes, funding, and proof packet status are checked.",
  },
  {
    key: "proof-packet",
    lane: "Save Proof",
    business: "SimpleePay",
    title: "Payroll proof packet waiting",
    amount: "3 packets",
    due: "After payroll",
    status: MONEY_STATUS.PROOF_MISSING,
    source: "payroll_packet",
    confidence: CONFIDENCE_LEVEL.NEEDS_PROOF,
    visibility: VISIBILITY_LEVEL.OWNER_ONLY,
    priority: 91,
    action: "Prepare proof packet",
    why: "The packet should download and archive after payroll is sent.",
  },
  {
    key: "mrktrade-paperwork",
    lane: "Tower Handoff",
    business: "MrkTrade",
    title: "Protected paperwork packet needs Tower review",
    amount: "$3.1k",
    due: "Protected",
    status: MONEY_STATUS.TOWER_REQUIRED,
    source: "tower_gated_snapshot",
    confidence: CONFIDENCE_LEVEL.TOWER_GATED,
    visibility: VISIBILITY_LEVEL.TOWER_REQUIRED,
    priority: 89,
    action: "Prepare Tower handoff",
    why: "The Teller can prepare money paperwork, but OB/trading details require The Tower.",
  },
  {
    key: "skincare-costs",
    lane: "Check Costs",
    business: "SimpleeSkincare",
    title: "Skincare costs need review",
    amount: "$740",
    due: "Soon",
    status: MONEY_STATUS.NEEDS_REVIEW,
    source: "manual_money_snapshot",
    confidence: CONFIDENCE_LEVEL.ESTIMATED,
    visibility: VISIBILITY_LEVEL.OWNER_ONLY,
    priority: 70,
    action: "Check costs",
    why: "Skincare money should separate sales, fees, refunds, shipping spend, and costs before showing net.",
  },
  {
    key: "route-proof",
    lane: "Attach Proof",
    business: "SimpleeOnTheGo",
    title: "Route proof missing",
    amount: "1 item",
    due: "This week",
    status: MONEY_STATUS.PROOF_MISSING,
    source: "route_money_record",
    confidence: CONFIDENCE_LEVEL.NEEDS_PROOF,
    visibility: VISIBILITY_LEVEL.OWNER_ONLY,
    priority: 68,
    action: "Attach route proof",
    why: "Route money needs receipts and cash movement records before being treated as clean.",
  },
  {
    key: "property-bills",
    lane: "Pay Bills",
    business: "SimpleeProperty",
    title: "Vendor bills need matching",
    amount: "3 bills",
    due: "Soon",
    status: MONEY_STATUS.NEEDS_REVIEW,
    source: "property_money_record",
    confidence: CONFIDENCE_LEVEL.ESTIMATED,
    visibility: VISIBILITY_LEVEL.OWNER_ONLY,
    priority: 62,
    action: "Review bills",
    why: "Property payments should match invoice, vendor, property, and proof before money moves.",
  },
];

export const ownerBusinessLanes = [
  {
    key: "simpleepay",
    title: "SimpleePay",
    personality: "payroll desk",
    summary: "$4.8k payroll waiting on final readiness",
    focus: "Pay people accurately, seal proof, and keep payroll records clean.",
    actions: ["Review payroll records", "Check pay-cycle readiness", "Send + seal proof"],
    color: "#92D7C8",
  },
  {
    key: "mrktrade",
    title: "MrkTrade",
    personality: "protected paperwork lane",
    summary: "$50.0k protected owner snapshot",
    focus: "Financial paperwork only. No OB access from The Teller.",
    actions: ["Prepare Tower handoff", "View vague numbers", "Check proof health"],
    color: "#BFA4FF",
    protected: true,
  },
  {
    key: "skincare",
    title: "SimpleeSkincare",
    personality: "money-only beauty counter",
    summary: "$2.6k business money snapshot",
    focus: "Sales, costs, fees, refunds, shipping spend, deposits, and proof records only.",
    actions: ["Review money", "Check costs", "Attach money proof"],
    color: "#FF9ED8",
  },
  {
    key: "onthego",
    title: "SimpleeOnTheGo",
    personality: "route money lane",
    summary: "$8.1k route revenue tracked",
    focus: "Route revenue, location fees, cash movement, machine costs, and route proof.",
    actions: ["Update route money", "Prepare payments", "Attach route proof"],
    color: "#5EEAD4",
  },
  {
    key: "property",
    title: "SimpleeProperty",
    personality: "property money ledger",
    summary: "$12.4k property income tracked",
    focus: "Income, vendor bills, reserves, repairs, taxes, insurance, and property paperwork.",
    actions: ["Check property money", "Review reserves", "Review property records"],
    color: "#A7C7E7",
  },
];

export const ownerCalmMode = {
  title: "Calm Money Mode",
  subtitle: "One thing at a time. Highest-priority money item first.",
  hideSections: ["snapshot_grid", "business_lane_grid"],
  showSections: ["today_focus", "single_action", "why_this_matters"],
};

export function getOwnerTheme(themeKey = ownerProfile.defaultTheme) {
  return ownerThemeChoices[themeKey] || ownerThemeChoices[ownerProfile.defaultTheme];
}

export function getTodayOwnerFocus(queue = ownerMoneyQueue) {
  return [...queue].sort((a, b) => Number(b.priority || 0) - Number(a.priority || 0))[0] || null;
}

export function getOwnerBusinessLane(key) {
  return ownerBusinessLanes.find((lane) => lane.key === key) || ownerBusinessLanes[0];
}
